name: Demo on self-hosted Docker runner

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:  # Add this to manually trigger for testing

jobs:
  hello:
    runs-on: [self-hosted]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Display system info
        run: echo "Hello from $(uname -a)"
      
      - name: Test Docker access
        run: |
          echo "Testing Docker functionality..."
          docker version
          docker run --rm alpine sh -c "echo '✅ Container executed successfully!' && uname -a"
      
      - name: Verify workspace
        run: |
          echo "Working directory: $(pwd)"
          ls -la